version: "3.8"
services:
  api:
    build:
      context: ./packages/api
    container_name: api.headache.phr
    environment:
      ENV: ${ENV:-develop}
      GIT_TAG: $GIT_TAG
      GIT_REVISION: $GIT_REVISION
    volumes:
      - ./packages/api:/packages/api
      - ./packages/schema:/packages/schema
    ports:
      - "3000:3000"

  postgresql:
    image: postgres:14.1-alpine
    container_name: postgres.headache.phr
    command: postgres -c max_connections=200
    environment:
      ENV: ${ENV:-develop}
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
    volumes:
      - ./util-containers/postgresql/data:/var/lib/postgresql/data
      - ./util-containers/postgresql/init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    restart: always

  # web-app:
  #   build:
  #     context: ./packages/webapp
  #   container_name: webapp.phr
  #   environment:
  #     ENV: ${ENV:-develop}
  #   volumes:
  #     - ./packages/webapp:/packages/webapp
  #     - ./packages/schema:/packages/schema
  #   ports:
  #     - "5000:5000"
  # -----------------------------------------
  # Util containers
  # -----------------------------------------

  # Migration service to relevant datastores.
  migrate:
    build:
      context: ./packages/migrate
    container_name: migrate.headache.phr
    environment:
      ENV: ${ENV:-develop}
      GIT_TAG: $GIT_TAG
      GIT_REVISION: $GIT_REVISION
    volumes:
      - ./packages/migrate:/packages/migrate
  vault:
    build:
      context: ./infra/vault
    container_name: vault.headache.phr
    environment:
      ENV: ${ENV:-develop}
      GIT_TAG: $GIT_TAG
      GIT_REVISION: $GIT_REVISION
    volumes:
      - ./infra/vault:/infra/vault
  schema:
    build:
      context: ./packages/schema
    container_name: schema.headache.phr
    environment:
      ENV: ${ENV:-develop}
      GIT_TAG: $GIT_TAG
      GIT_REVISION: $GIT_REVISION
    volumes:
      # Exclude container directory overwritten by host.
      - /packages/schema/node_modules
      - ./packages/schema:/packages/schema
    ports:
      - "4000:4000"
